server:
  port: 8080

spring:
  sql:
    init:
      mode: always
  application:
    name: webSocket

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        id:
          new_generator_mappings: false
        jdbc:
          lob.non_contextual_creation: true
          order_inserts: true
          order_updates: true
          batch_size: 30

  datasource:
    url: jdbc:postgresql://${DATABASE_URL}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

